### ISSUE TITLE
Mobile Polishing - Consider placing navigation links in App Header into a hamburger menu when in mobile

### ISSUE THREAD

**Issue by halocline** [grommet/grommet-tools#72]
Consider placing navigation links in App Header into a hamburger menu when in mobile. The text links get crowded, especially on smaller screens. Collapsing them into a hamburger menu could help here and would also prevent the need to wrap the App Title.

![Screen Shot 2020-08-04 at 10 29 01 AM](https://user-images.githubusercontent.com/1756948/89319475-61c6f780-d63d-11ea-91b7-e9f0f6ca12d7.png)

**Comment by ShimiSun** [comment]
Agreed, similar to https://storybook.grommet.io/?path=/story/nav--collapsable-nav.
