### ISSUE TITLE
Inconsistent button padding on Feedback page

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-tools#74]
Because the buttons are uniform size but the length of the labels differs, it's creating inconsistent horizontal padding on the button. It is subtle, but wondering if we should let buttons respond to the width of their content
<img width="517" alt="Screen Shot 2020-08-04 at 9 15 19 AM" src="https://user-images.githubusercontent.com/12522275/89320049-d4cc7000-d635-11ea-8491-6b86604c7d03.png">

**Comment by ShimiSun** [comment]
I was surprised by this behavior as well. 
After discussing with Marisa, the designs are using align-center for the content, hence when the text is longer/shorter the padding shrinks/grow. 
@jcfilben & @JoeButler7 can you take this feedback to Marisa? seems like I wasn't the only one that found it inconsistent.
