### ISSUE TITLE
Remove placeholder text of file name

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-tools#75]
For now, I would either remove the placeholder text for file name if it's not being pulled in dynamically, or just hard code the name:
<img width="473" alt="Screen Shot 2020-08-04 at 9 36 46 AM" src="https://user-images.githubusercontent.com/12522275/89320360-3db3e800-d636-11ea-8f79-3218316a3237.png">

**Comment by ShimiSun** [comment]
We'll remove that placeholder text for now, but we'll need to work with Marisa on images per tool and relevant text titles in case she would like to keep it.
