### ISSUE TITLE
"deisgner" typo

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-tools#79]
<img width="233" alt="Screen Shot 2020-08-04 at 10 27 27 AM" src="https://user-images.githubusercontent.com/11637956/89325077-24fb0080-d63d-11ea-8cce-91d8f0dc2639.png">

**Comment by ShimiSun** [comment]
Good catch.
@JoeButler7 @jcfilben there are good IDEA extensions that help with spell checks and help you avoid publishing typos to production.
For reference, this is the extension I'm using https://github.com/streetsidesoftware/vscode-spell-checker, it's a good practice for the long run.
